<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * CarrerasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarrerasRepository extends \Doctrine\ORM\EntityRepository
{
	public function obtenerCarreras(){

		$em = $this->getEntityManager();

		$query ="
	        SELECT ca.id as id, ca.nombre as nombre
			FROM AdminBundle:Carreras ca
	   ";

	   $sql = $em->createQuery($query);

	   $oCarreras = $sql->getResult();

	   return $oCarreras;
	}
}
