<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * ChatsMensajesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatsMensajesRepository extends \Doctrine\ORM\EntityRepository
{

	public function obtenerPermisosChats(){
		
	}
	// public function obtenerChatsMensajes($id_chat){

	//       $em = $this->getEntityManager();

	//       $query ="
	//         SELECT  mens.id, us.nombre as novatoNombre, us.apellidos as novatoApellidos, mens.contadorSinResponder, 
	//                mens.createdAt, es.id as idEstado 
	// 		FROM AdminBundle:ChatsMensajes mens
	// 		LEFT JOIN AdminBundle:Chats ch WITH ch.id = mens.idChat
	// 		LEFT JOIN AdminBundle:Usuarios us WITH us.id = mens.idUsuario
	// 		LEFT JOIN AdminBundle:Estados es WITH es.id = mens.idEstado
	// 		WHERE 1=1 AND  mens.idChat = :id_chat
	//       ";
	   
	//     $sql = $em->createQuery($query);
	//     $sql->setParameter('id_chat', $id_chat);

	//     $aChatsMensajes = $sql->getResult();

	//     return $aChatsMensajes;        
 //    }
}
