<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * ContenidoMultimediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenidoMultimediaRepository extends \Doctrine\ORM\EntityRepository
{
}
