<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * EstadosMultimediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadosMultimediaRepository extends \Doctrine\ORM\EntityRepository
{
}
