<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * EstadosUsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadosUsuariosRepository extends \Doctrine\ORM\EntityRepository
{
}
