<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * InfoPuntosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoPuntosRepository extends \Doctrine\ORM\EntityRepository
{
}
