<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * RegionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionesRepository extends \Doctrine\ORM\EntityRepository
{
}
