<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * relEstandMultimediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelEstandMultimediaRepository extends \Doctrine\ORM\EntityRepository
{
	public function obtenerMultimediasStands($id_stand){
		$em = $this->getEntityManager();
		
		$query ="
	        SELECT contenidoMul.id as idContenidoMultimedia,  contenidoMul.nombre as nombre, contenidoMul.url as url, contenidoMul.codigoYoutube as  codigoYoutube, contenidoMul.createdAt as createdAt, contenidoMul.updatedAt as updatedAt, tipoMul.nombre as tipoMultimedia,estadoMul.id as idEstadoMultimedia
			FROM AdminBundle:RelEstandMultimedia relStandMult
			LEFT JOIN AdminBundle:ContenidoMultimedia contenidoMul WITH contenidoMul.id = relStandMult.idContenidoMultimedia
			LEFT JOIN AdminBundle:EstadosMultimedia estadoMul WITH estadoMul.id = contenidoMul.idEstadoMultimedia
			LEFT JOIN AdminBundle:tiposMultimedia tipoMul WITH tipoMul.id = contenidoMul.idTipoMultimedia
			LEFT JOIN AdminBundle:Stands sta WITH sta.id = relStandMult.idStand
			WHERE 1=1 
			AND contenidoMul.idEstadoMultimedia in(1,2)
			AND sta.id = :id_stand
       ";

		$sql = $em->createQuery($query);
		$sql->setParameter('id_stand', $id_stand);

		$aRelEstandMultimedia  = $sql->getResult();

		return $aRelEstandMultimedia;
	}
}
