<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * TiposMultimediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposMultimediaRepository extends \Doctrine\ORM\EntityRepository
{
}
