<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * TiposPuntoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiposPuntoRepository extends \Doctrine\ORM\EntityRepository
{
}
