<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * UsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends \Doctrine\ORM\EntityRepository
{
	public function obtenerUsuarios($fecha_inicio, $fecha_termino){

		$em = $this->getEntityManager();

		$query ="
	        SELECT user.id as id, user.rut as rut, user.nombre as nombre, user.apellidos as apellidos, user.username as username, user.createdAt as createdAt, user.updatedAt as updatedAt, es.id as idEstadoUsuario, regi.nombre as region, comu.nombre as comuna, cole.nombre as colegio, user.carreras as carreras, user.telefono as telefono, visi.nombre as visita, user.opcionVisitante as opcionVisitante,
	            user.opcionColegio as opcionColegio, user.ensayo as ensayo, user.condiciones as condiciones, user.imagenPerfil as imagenPerfil
			FROM AdminBundle:Usuarios user
			LEFT JOIN AdminBundle:EstadosUsuarios es WITH es.id = user.idEstadoUsuario
			LEFT JOIN AdminBundle:Regiones regi WITH regi.id = user.idRegion
			LEFT JOIN AdminBundle:Comunas comu WITH comu.id = user.idComuna
			LEFT JOIN AdminBundle:Colegios cole WITH cole.id = user.idColegio
			LEFT JOIN AdminBundle:Visitantes visi WITH visi.id = user.idVisitante
			WHERE 1=1 AND user.idEstadoUsuario in(1,2)
			AND  user.createdAt between ?3 AND ?4
	   ";

	   $sql = $em->createQuery($query);
	   $sql->setParameter(3, $fecha_inicio);
	   $sql->setParameter(4, $fecha_termino);

	   $aUsuarios = $sql->getResult();

	   return $aUsuarios;
	}
    
    public function carrerasPorUsuario($carreras){

    	$em = $this->getEntityManager();

    	$query ="
	        SELECT ca.id as id, ca.nombre as nombre
			FROM AdminBundle:Carreras ca
			WHERE 1=1 AND ca.id IN(:carreras)
	   ";

	   $sql = $em->createQuery($query);
	   $sql->setParameter('carreras', explode(',', $carreras));

	   $oCarreras = $sql->getResult();
	   
	   return $oCarreras;
    }
}
