<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * ChatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatsRepository extends \Doctrine\ORM\EntityRepository
{
	public function obtenerChats(){

	    $em = $this->getEntityManager();

	  	$query ="
	        SELECT ch.id as id, ch.nombre as nombre, ch.diasFuncionamiento as diasFuncionamiento, ch.horaApertura as horaApertura, ch.horaCierre, ch.createdAt as createdAt, ch.updatedAt as updatedAt, es.nombre as esatadoNombre, es.id as idEstado
			FROM AdminBundle:Chats ch
			LEFT JOIN AdminBundle:Estados es WITH es.id = ch.idEstado 
			WHERE 1=1 AND ch.idEstado in(1,2)
	   ";

	   $sql = $em->createQuery($query);
	  
	   $aChats = $sql->getResult();

	   return $aChats;        
    }

    public function obtenerChatsPorEmbajador($id_administrador){

    	$em = $this->getEntityManager();

      	$query ="
	        SELECT ch.id as id, ch.nombre as nombre, ch.diasFuncionamiento as diasFuncionamiento, ch.horaApertura as horaApertura, ch.horaCierre, ch.createdAt as createdAt, ch.updatedAt as updatedAt, es.nombre as esatadoNombre, es.id as idEstado
			FROM AdminBundle:PermisosChatsAdministradores per
			LEFT JOIN AdminBundle:Administradores ad WITH ad.id = per.idAdministrador
			LEFT JOIN AdminBundle:Chats ch WITH ch.id = per.idChat
			LEFT JOIN AdminBundle:Estados es WITH es.id = ch.idEstado 
			WHERE 1=1 AND ch.idEstado in(1,2) AND per.idAdministrador = :id_administrador
       ";

        $sql = $em->createQuery($query);
	    $sql->setParameter('id_administrador', $id_administrador);

	    $aChats = $sql->getResult();

	    return $aChats;
    }
}
