<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * ComunasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComunasRepository extends \Doctrine\ORM\EntityRepository
{
}
