<?php

namespace FeriaUC\AdminBundle\Repository;

/**
 * StandsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandsRepository extends \Doctrine\ORM\EntityRepository
{
	public function obtenerStandsPorCategoria($id_punto, $id_categoria){

		$em = $this->getEntityManager();

		$query ="
	        SELECT st.id as id, st.nombre as nombre
			FROM AdminBundle:Stands st
			LEFT JOIN AdminBundle:Estados es WITH es.id = st.idEstado
			LEFT JOIN AdminBundle:Puntos pu WITH pu.id = st.idPunto
			LEFT JOIN AdminBundle:Categorias cat WITH cat.id = st.idCategoria
			WHERE 1=1 
			AND st.idEstado = 1 
			AND pu.id = :id_punto
			AND cat.id = :id_categoria
	   ";

	   $sql = $em->createQuery($query);
	   $sql->setParameter('id_punto', $id_punto);
	   $sql->setParameter('id_categoria', $id_categoria);


	   $aStands = $sql->getResult();

	   return $aStands;
	}
}
